filename = 'C:\Users\mad.exe\Desktop\proj\final project\sat_train_modified.txt';
filename1 = 'C:\Users\mad.exe\Desktop\proj\final project\sat_test_modified.txt';
filename2 = 'C:\Users\mad.exe\Desktop\proj\abalone_nav_bayes.txt';
M = csvread(filename);
M1 = csvread(filename1);
[rows, cols] = size(M);
[rows1, cols1] = size(M1);
X = M(1: rows, 1:cols - 1);
Y = M(1:rows, cols);
delete filename2;
navbay = NaiveBayes.fit(X, Y);
X = M1(1: rows1, 1:cols1 - 1);
Y = M1(1: rows1, cols1);
c1 = navbay.predict(X);
ans = [Y, c1];
disp(ans);
dlmwrite(filename2, ans, '\n');
cmat = confusionmat(Y, c1);
%disp(cmat);
acc1 = 100*sum(diag(cmat))/sum(cmat(:));
disp(acc1);